nodeLinker: node-modules

npmRegistries:
  //git.hda.onl/api/v4/projects/58/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: q5b3dm5eyC9-vxuEB-nV

npmScopes:
  exam-libraries:
    npmAlwaysAuth: true
    npmAuthToken: q5b3dm5eyC9-vxuEB-nV
    npmRegistryServer: "https://git.hda.onl/api/v4/projects/58/packages/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
